BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models;
using Bulky.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
	{
        private readonly IUnitOfWork unitOfWork;
        public CompanyController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        public IActionResult Index()
		{
            
			List<Company> companies = unitOfWork.Company.GetAll().ToList();
			return View(companies);
		}
		public IActionResult Upsert(int? id)
		{

			Company company = new Company();

			if (id == null || id == 0)
			{
				// create
				return View(company);
			}
			else
			{
				// update
				company = unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
				return View(company);
			}
		}
		[HttpPost]
		public IActionResult Upsert(Company company)
		{
			if (ModelState.IsValid)
			{

				if (company.Id == 0)
				{
					unitOfWork.Company.Add(company);
				}
				else
				{
					unitOfWork.Company.Update(company);
				}

				unitOfWork.Save();
				TempData["success"] = "Company created successfully";
				return RedirectToAction(nameof(Index));
			}
			else
			{
				return View(company);
			}

		}

		#region APICALLS
		[HttpGet]
		public IActionResult GetAll()
		{
			List<Company> companies = unitOfWork.Company.GetAll().ToList();
			return Json(new { data = companies });
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			Company? companyToBeDeleted = unitOfWork.Company.GetFirstOrDefault(u => u.Id == id);
			if (companyToBeDeleted == null)
			{
				return Json(new { success = false, message = "Error while deleting" });
			}

			unitOfWork.Company.Remove(companyToBeDeleted);
			unitOfWork.Save();

			return Json(new { success = true, message = "Delete successful" });
		}
		#endregion
	}
}

BulkyWeb/Areas/Admin/Views/Company/Index.cshtml
@model List<Company>

<div class="container">
	<div class="row pt-4 pb-3">
		<div class="col-6">
			<h2 class="text-primary">
				Company List
			</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="Company" asp-action="Upsert" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i>
				Create New Company
			</a>
		</div> 
	</div>
	<table class="table table-bordered table-striped" id="tblData" style="width: 100%">
		<thead>
			<tr>
				<th>
					Name
				</th>
				<th>
					Address
				</th>
				<th>
					City
				</th>
				<th>
					State
				</th>
				<th>
					PhoneNumber
				</th>
				<th>

				</th>
			</tr>
		</thead>
	</table>
</div>

@section Scripts {
	<script src="~/js/company.js"></script>
}

BulkyWeb/Areas/Admin/Views/Company/Upsert.cshtml
@model Company

<form method="post">
	<input asp-for=Id hidden />
	<div class="row">
		<div class="col border p-3 mt-4">
			<div class="row pb-2">
				<h2 class="text-primary">@(Model.Id != 0 ? "Update" : "Create") Company</h2>
				<hr />
			</div>

			@*<div asp-validation-summary=All></div>*@
			<div class="mb-3 row p-1">
				<label asp-for=Name class="p-0"></label>
				<input asp-for=Name type="text" class="form-control" />
				<span asp-validation-for=Name class="text-danger"></span>
			</div>
			<div class="mb-3 row p-1">
				<label asp-for=StreetAddress class="p-0 text-muted"></label>
				<input asp-for=StreetAddress type="text" class="form-control" />
				<span asp-validation-for=StreetAddress class="text-danger"></span>
			</div>
			<div class="mb-3 row p-1">
				<label asp-for=City class="p-0"></label>
				<input asp-for=City type="text" class="form-control" />
				<span asp-validation-for=City class="text-danger"></span>
			</div>
			<div class="mb-3 row p-1">
				<label asp-for=State class="p-0"></label>
				<input asp-for=State type="text" class="form-control" />
				<span asp-validation-for=State class="text-danger"></span>
			</div>
			<div class="mb-3 row p-1">
				<label asp-for=PostalCode class="p-0"></label>
				<input asp-for=PostalCode type="text" class="form-control" />
				<span asp-validation-for=PostalCode class="text-danger"></span>
			</div>
			<div class="mb-3 row p-1">
				<label asp-for=PhoneNumber class="p-0"></label>
				<input asp-for=PhoneNumber type="text" class="form-control" />
				<span asp-validation-for=PhoneNumber class="text-danger"></span>
			</div>
			<div class="row">
				<div class="col-6 col-md-3">
					<button type="submit" class="btn btn-primary form-control">@(Model.Id != 0 ? "Update" : "Create")</button>
				</div>
				<div class="col-6 col-md-3">
					<a asp-controller="Company" asp-action="Index" class="btn btn-outline-secondary border form-control">Back To List</a>
				</div>
			</div>
		</div>
	</div>

</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}